package com.github.catvod.spider.merge.I1;

import com.github.catvod.spider.merge.l.C1290c;
import com.github.catvod.spider.merge.m1.EnumC1316h;

/* JADX INFO: loaded from: /tmp/decompiler/3c5abd9eeb9c4becbc43dcd6f345eaa4/classes.dex */
public final class n {
    private String a;
    private String b;
    private boolean c;
    private EnumC1316h d;
    private String e;
    private Boolean f;

    public final o a() {
        if (this.b == null) {
            throw new IllegalStateException("No valid content was specified. Please specify a valid one with setContent.");
        }
        String str = this.e;
        if (str == null) {
            throw new IllegalStateException("The language code of the subtitles stream has been not set or is null. Make sure you specified an non null language code with setLanguageCode.");
        }
        if (this.f == null) {
            throw new IllegalStateException("The subtitles stream has been not set as an autogenerated subtitles stream or not. Please specify this information with setIsAutoGenerated.");
        }
        if (this.a == null) {
            EnumC1316h enumC1316h = this.d;
            this.a = C1290c.a(str, enumC1316h != null ? C1290c.a(".", enumC1316h.c) : "");
        }
        return new o(this.a, this.b, this.c, this.d, this.e, this.f.booleanValue());
    }

    public final n b(boolean z) {
        this.f = Boolean.valueOf(z);
        return this;
    }

    public final n c(String str) {
        this.b = str;
        this.c = true;
        return this;
    }

    public final n d(String str) {
        this.e = str;
        return this;
    }

    public final n e(EnumC1316h enumC1316h) {
        this.d = enumC1316h;
        return this;
    }
}
